logging:
  level: INFO
  loggers:
    com.ikea.vaexabox: DEBUG
    
server:
  applicationConnectors:
  - type: http 
    port: 8880
  adminConnectors:
  - type: http
    port: 8881

    
dburl: jdbc:sqlite:IKEAHelpMe.sqlite
      