logging:
  level: INFO
  loggers:
    com.ikea.vaexabox: DEBUG
    
server:
  applicationConnectors:
  - type: http 
    port: 8880
  adminConnectors:
  - type: http
    port: 8881
    
dburl: jdbc:sqlite:IKEAHelpMe.sqlite
      
raspi: bedrooms

sendmail: 0
smtphost: smtp.strato.de
smtpport: 587
smtpuser: raspi@egladil.de
smtppassword: test0815


initDisplay1: Press Button 
initDisplay2: for Help Please!

onEventDisplay1: IKEA Co-Worker 
onEventDisplay2: is informed!

onAcceptDisplay1: IKEA Co-worker
onAcceptDisplay2: is coming soon!

onMannedDisplay1: Welcome
onMannedDisplay2: at IKEA!


